server:
  port: 8888

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file://${user.home}/ssafy/native-file-repo
#          search-locations: file:C:\SSAFY\native-file-repo
#        git:
#          uri: file://C:\SSAFY\project
#          uri: https://lab.ssafy.com/s09-webmobile1-sub2/S09P12C204
#          default-label: feature/S09P12C204-359-msa