server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file:///Users/dong82/project/kkoch
          default-label: feature/S09P12C204-359-msa