server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: file://C:\SSAFY\project
          default-label: feature/S09P12C204-359-msa